ALTER TABLE public.services ADD COLUMN details text;

UPDATE public.services SET details = E'Our security guards and guardettes are the frontline of your protection. Every officer is vetted, uniformed and trained in access control, incident reporting, fire safety and customer service. We provide male and female guards for corporate offices, residential estates, retail outlets, warehouses and industrial plants, with supervision and regular patrols to maintain discipline and responsiveness. Whether you need a static post or a roving presence, we match the right officer to your risk profile and site culture.' WHERE title = 'Security Guards & Guardettes';

UPDATE public.services SET details = E'Home security should be discreet, reliable and proactive. We protect private homes, gated communities and apartment blocks with trained residential guards, scheduled patrols, visitor management and integration with alarm and CCTV systems. Our teams understand the importance of courtesy, confidentiality and rapid escalation, giving residents peace of mind around the clock.' WHERE title = 'Residential Security';

UPDATE public.services SET details = E'Commercial properties face unique risks: theft, unauthorised access, after-hours intrusions and customer incidents. We secure offices, banks, hotels, restaurants, shops and malls with tailored guarding schedules, access protocols, loss-prevention support and emergency response plans. Our officers represent your brand professionally while keeping people, stock and premises safe.' WHERE title = 'Commercial Security';

UPDATE public.services SET details = E'Industrial sites demand robust perimeter defence, strict access control and awareness of hazardous areas. We protect factories, warehouses, construction sites and distribution centres with perimeter patrols, gate control, asset monitoring, fire-watch duties and safety compliance support. Our supervisors coordinate closely with plant management to align security with operational shifts.' WHERE title = 'Industrial Security';

UPDATE public.services SET details = E'Our VIP protection service provides trained close-protection officers for executives, dignitaries, celebrities and high-net-worth individuals. We conduct advance route planning, threat assessment, venue sweeps and discreet escort services, balancing high vigilance with low visibility. Every detail is planned so you can focus on your business or event.' WHERE title = 'VIP Protection';

UPDATE public.services SET details = E'From corporate functions and concerts to weddings and sports events, our event security teams manage crowd flow, access control, ticket verification, emergency evacuations and incident response. We work with organisers, police and medical teams to keep guests safe and events running smoothly from setup to breakdown.' WHERE title = 'Event Security';

UPDATE public.services SET details = E'Mobile patrols extend your security coverage without the cost of a full-time guard. Our branded motorcycles and vehicles conduct random or scheduled patrols of estates, commercial parks and industrial sites, checking for intrusions, vandalism, fire risks and safety hazards. GPS tracking ensures accountability and rapid dispatch when alarms are triggered.' WHERE title = 'Mobile Patrol';

UPDATE public.services SET details = E'When an alarm sounds, every second counts. Our 24/7 control room dispatches the nearest response unit to your premises immediately. We coordinate with property managers, alarm providers and emergency services to secure the site, investigate the cause and provide a full incident report. Back-up units are always on standby for larger threats.' WHERE title = 'Alarm Response & Back-up';

UPDATE public.services SET details = E'We design, supply and install high-definition CCTV systems for homes, businesses and public spaces. Our solutions include dome and bullet cameras, night vision, remote viewing apps, motion detection and secure cloud or local storage. Systems are scaled to your budget and coverage needs, with clean cable management and minimal disruption during installation.' WHERE title = 'CCTV Installation';

UPDATE public.services SET details = E'Our control room provides live remote monitoring of your CCTV feeds, watching for suspicious activity, perimeter breaches and safety incidents in real time. Trained operators follow agreed response protocols, including audio warnings, alarm activation and dispatch of mobile response units. Monitoring is available for sites with or without on-site guards.' WHERE title = 'CCTV Monitoring';

UPDATE public.services SET details = E'Control who enters your premises with modern access control systems. We install and maintain card readers, keypads, intercoms, boom barriers and turnstiles, integrated with time-and-attendance or visitor-management software. Access rights can be managed centrally, with audit trails that improve accountability and simplify investigations.' WHERE title = 'Access Control Systems';

UPDATE public.services SET details = E'Biometric systems use unique physical identifiers such as fingerprints or facial recognition to grant access. Ideal for high-security offices, data centres, factories and sensitive facilities, these systems eliminate lost cards and PIN sharing while producing detailed entry logs. We integrate biometrics with existing doors, gates and payroll systems.' WHERE title = 'Biometric Systems';

UPDATE public.services SET details = E'Our electric fence installations provide a powerful physical and psychological deterrent against intruders. We use certified energizers, high-tensile wires, warning signs and compliance with Kenyan safety standards. Systems can be linked to alarm panels and strobe lights, delivering instant alerts when the perimeter is tampered with.' WHERE title = 'Electric Fence Installation';

UPDATE public.services SET details = E'Our security dog services combine highly trained detection and deterrence dogs with experienced handlers. Dogs are deployed for property patrols, event security, cargo screening, narcotics detection and high-risk site protection. Each K9 team is a visible deterrent and a rapid response asset, capable of covering large areas quickly.' WHERE title = 'Security Dog Services';

UPDATE public.services SET details = E'We supply, install and maintain intruder alarm systems for residential, commercial and industrial properties. Solutions include door and window sensors, motion detectors, glass-break sensors, panic buttons, sirens and smart app notifications. Systems are monitored locally or connected to our 24/7 response centre for immediate action.' WHERE title = 'Intruder Alarm Systems';

UPDATE public.services SET details = E'Know where your vehicles are, how they are driven and how fuel is consumed. Our GPS tracking and fleet management service provides real-time location tracking, route history, geofencing, speed alerts, fuel monitoring and maintenance reminders. Reports help you cut costs, improve driver behaviour and recover assets quickly in case of theft.' WHERE title = 'Car Tracking & Fleet Management';

UPDATE public.services SET details = E'Our security consultants review your operations, physical environment and threat landscape to build a practical protection strategy. We advise on guard deployment, technology integration, policies, emergency plans and compliance requirements, helping you spend wisely while closing real security gaps.' WHERE title = 'Security Consultancy';

UPDATE public.services SET details = E'Our risk assessments identify threats, vulnerabilities and consequences specific to your site or activity. We inspect premises, review procedures, interview staff and analyse incident history, then deliver a prioritised action plan with costed recommendations. This service is ideal for new facilities, insurance requirements or annual security reviews.' WHERE title = 'Risk Assessment';

UPDATE public.services SET details = E'Alarm systems are only effective when they are properly designed, installed and maintained. We assess your premises, recommend the right mix of sensors and control panels, carry out professional installation and provide user training. Ongoing maintenance and remote diagnostics keep your system ready to protect you day and night.' WHERE title = 'Alarm Installation';